version: '2'

services:
  load:
    build:
      context: ./module
      dockerfile: Dockerfile.template
      args:
        # Modify to the desired balenaOS version
        OS_VERSION: 5.0.8
    expose: 
      - "8000"
    ports:
      - "8000"
    privileged: true
    labels:
      io.balena.features.kernel-modules: 1
    restart: on-failure

  check:
    build:
      context: ./check
      dockerfile: Dockerfile.template
    depends_on:
      - load
